import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import SideMenu from "@/components/sideMenu/sideMenu";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "flex flex-row",
          "p-[var(--panel-gap)]"
        )}
      >
        <SideMenu />
        {children}
      </body>
    </html>
  );
}
